# Generated by Django 5.0.1 on 2024-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_finch_location_finch_name_alter_finch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='image',
            field=models.ImageField(default='all-finches/{finch.id}/image.jpg', upload_to='all-finches/{finch.id}'),
        ),
        migrations.AlterField(
            model_name='finch',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
