# Generated by Django 5.0.1 on 2024-01-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_finch_image_alter_finch_location_alter_finch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='image',
            field=models.ImageField(default='None', upload_to='all-finches/{finch.id}'),
        ),
    ]
