# Generated by Django 5.0.1 on 2024-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_finch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='image',
            field=models.ImageField(upload_to='all-finches/{finch.id}'),
        ),
    ]
